### ISSUE TITLE
IAgentClass vs String Identifier

### ISSUE THREAD

**Issue by JeremyWildsmith** [JeremyWildsmith/bazaarbot-java#16]
I think we should replace the String identifier for agent class with IAgentClass like was done with ICommodity.

The way it is now, the agent class is decoupled from logic, ideal and start goods. I think IAgentClass should expose getStart, getIdeal, getLogic; then we can implement it as an enum like what was done with ICommodity. This puts all the data / behavior for an agent class in the same place.

**Comment by DigitalSmile** [comment]
Agree. Will make it in refactoring tree.
