### ISSUE TITLE
Things that need to be factored out

### ISSUE THREAD

**Issue by JeremyWildsmith** [JeremyWildsmith/bazaarbot-java#21]
The market update loop is setting agent's "moneyEarnedLastRound" field.

Two problems with this:
- Logic is fixed to round - based mechanism, which isn't idea.
- It seems like the responsibility with the field should not be with the BasicAgent class. It doesn't make sense for the behaviour for this field to be implemented in a totally different class.

I think this follows that the "getProfit" field need to be removed as well. Profit needs a record of previous balance, which is more of a history thing.

**Comment by DigitalSmile** [comment]
I did some improvements in refactoring branch. Especially with naming. Let's first make the refactoring code get merged :)
As for the topic I would agree... History thing is also quite strange to me. It should be like a log or statistics, which is used internally by engine without any outbound calls. I think we have to rename the History thing and make it more internal.
